app:
  env: local
  httpaddr: 127.0.0.1
  httpport: 3001
  maindomain: https://www.example.com/

db:
  driver: mysql
  host: localhost
  port: 3306
  name: database
  user: root
  password: root

mail:
  driver: smtp
  host: mailtrap.io
  port: 25
  username:
  password:
  encryption: tls
  fromaddress: noreply@example.com
  fromname: example.com

jwt:
  secret: secret
  ttl: 525600